spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./database
    username: sa
    password: sa
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect